.TH ESVALIDATE "1" "June 2016" "ECMAScript Validator" "User Commands"
.SH NAME
esvalidate \- ECMAScript Validator using Esprima
.SH DESCRIPTION
.SS "Usage:"
.IP
esvalidate [options] file.js
.PP
Available options:
.TP
\fB\-\-format\fR=\fI\,type\/\fR
Set the report format, plain (default) or junit
.TP
\fB\-v\fR, \fB\-\-version\fR
Print program version
